### ISSUE TITLE
Update nightwatch to latest release

### ISSUE THREAD

**Issue by YesCT** [Lullabot/drainpipe-dev#55]

**Comment by YesCT** [comment]
See https://github.com/Lullabot/lullabot.com-d8/pull/2153#issuecomment-1259586470 for background.

**Comment by justafish** [comment]
@YesCT This package doesn't control which version of nightwatch you're using

**Comment by deviantintegral** [comment]
@justafish the problem is our config isn't compatible anymore as nightwatch-axe was added to nightwatch itself. If you upgrade to 2.3.6 or higher things break.

https://github.com/Lullabot/drainpipe-dev/blob/05a0f72a526fa296b9acc6fbe49b42a3ed03ad1c/config/nightwatch.conf.js#L9

https://github.com/nightwatchjs/nightwatch/pull/3389

**Comment by justafish** [comment]
@deviantintegral there's already an issue open for that: #54

**Comment by deviantintegral** [comment]
that I filed 🤦
